### ISSUE TITLE
Deleting symlinks in /bin and /sbin is pointless

### ISSUE THREAD

**Issue by amacneil** [jumanjihouse/docker-duoauthproxy#47]
The `/runtime/harden.sh` script contains a bunch of deletion of system files, including useful tools like `chown` and `chmod`.

Deleting these make it harder to extend your image in another Dockerfile (e.g. to overwrite the authproxy.cfg file).

Finally, this is not hardening the container at all, because these files you are deleting do not contain any binary code, they are simply symlinks to `/bin/busybox`:

```sh
$ docker run -it alpine sh
/ # ls -al /bin/ch*
lrwxrwxrwx    1 root     root            12 Apr  1 18:56 /bin/chgrp -> /bin/busybox
lrwxrwxrwx    1 root     root            12 Apr  1 18:56 /bin/chmod -> /bin/busybox
lrwxrwxrwx    1 root     root            12 Apr  1 18:56 /bin/chown -> /bin/busybox
```

It is trivial to work around your hardening by calling busybox with the binary name:

```
$ docker run -it duoauthproxy sh
/ # busybox chown
BusyBox v1.24.1 (2015-12-16 08:00:02 GMT) multi-call binary.

Usage: chown [-RhLHPcvf]... OWNER[<.|:>[GROUP]] FILE...
```

Or by overriding the process name (python example):

```
$ docker run -it duoauthproxy sh
/ $ python -c 'import os; os.execl("/bin/busybox", "chown")'
BusyBox v1.24.1 (2015-12-16 08:00:02 GMT) multi-call binary.

Usage: chown [-RhLHPcvf]... OWNER[<.|:>[GROUP]] FILE...
```

Please consider removing this part of `harden.sh` as I don't believe they are adding to the security of the image, and make it harder to extend.

**Comment by jumanjiman** [comment]
@amacneil please take a look at https://github.com/jumanjihouse/docker-duoauthproxy/pull/50

**Comment by jumanjiman** [comment]
closed via PR.

thanks for the issue!

**Comment by jumanjiman** [comment]
train went underground previously. close for real.
